# Generated by Django 3.1.7 on 2021-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.TextField(max_length=64)),
                ('company', models.TextField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
