# Generated by Django 3.1.7 on 2021-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_checker', '0002_auto_20210323_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='company',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
