# Generated by Django 3.1.7 on 2021-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_checker', '0003_auto_20210323_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'ordering': ['-create_date'], 'verbose_name_plural': 'ip addresses'},
        ),
        migrations.AddField(
            model_name='ip',
            name='host',
            field=models.TextField(max_length=512, null=True),
        ),
    ]
