# Generated by Django 3.1.7 on 2021-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_checker', '0004_auto_20210324_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='asn_description',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='emails',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='real_address',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
