# Generated by Django 3.1.7 on 2021-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_checker', '0005_auto_20210324_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='company',
        ),
        migrations.AddField(
            model_name='ip',
            name='city',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='country',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='asn_description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='emails',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='host',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
