# Generated by Django 3.1.7 on 2021-03-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_checker', '0008_ip_ptr_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='ip_range',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
